version: '3'

services:
  node:
    build:
      context: node
    networks:
      - main
    tty: true
    volumes:
      - ./node:/app
    depends_on:
      - mysql
  nginx:
    build:
      context: nginx
    networks:
      - main
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - node
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=node
      - MYSQL_USER=node
      - MYSQL_DATABASE=node
      - MYSQL_INITDB_SKIP_TZINFO:yes
    networks:
      - main
    tty: true
    restart: always
    volumes:
      - ./mysql/dump:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql
networks:
  main:
